# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # You may pin to the exact commit or the version.
    # uses: b3b00/coverlet-action@ea67400f084993d98cfb3e2ec5948197d80a7d4e
    uses: b3b00/coverlet-action@1.1.1
    with:
      # output filename
      output: # default is ./lcov.info
      # output format : lcov, json, opencover, corbertura, temacity (see coverlet documentation)
      outputFormat: # default is lcov
      # assemblies, namespances exclusions (see coverlet documentation)
      excludes: # optional
      # path to unit test project from repository root
      testProject: 
